### ISSUE TITLE
Frameworks and Libraries

### ISSUE THREAD

**Issue by GaryJones** [Ipstenu/wporg-plugin-guidelines#21]
I may have missed it, but I couldn't see anything in the guidelines regarding the acceptance of frameworks and library plugins, that exist purely to avoid having to include said code directly in plugins or themes. 

Related, I also didn't spot anything about bundling other non-main plugins i.e. Plugin A including TGMPA with bundled Plugin B.

**Comment by Ipstenu** [comment]
Yeah you didn't. That _still_ falls under G18

> We reserve the right to arbitrarily disable or remove any plugin from the directory for any reason whatsoever, even for reasons not explicitly covered by these guidelines.

Why? Well... Of all the _possible_ guidelines out there, I think that's the one with the biggest opportunity to be changed. It really is a "right now" sort of thing. IF we get things like plugin dependancies and such working, then it'll be unnessecary and most of the reasons we have for not allowing them go away.

https://core.trac.wordpress.org/ticket/22316 comes to mind...

Also we do allow TGMPA to be included in a plugin today so ... I'm not sure what you're talking about by bundling? Unless you mean "Please don't include a plugin that's _already_ in the repo inside your own plugin"?

Again, **IF** core gets plugin dependancies working, we can stop caring about a lot of that and treat it like parent/child themes. Woo.

Yes, we could make an explicit rule of "A plugin has to do 'something' and not just be a library" that has to be called by other plugins... Certainly that's up for debate. It's actually an exceptionally rare case for it to come up, and most of the time it's pretty clear cut.

**Comment by GaryJones** [comment]
> Unless you mean "Please don't include a plugin that's already in the repo inside your own plugin"?

Yes, this, although I can't remember off the top of my head whether plugins that might otherwise only be sourced from GitHub or other VCS repo, which are bundled (as a zip, which is probably against the rules anyway) as well would be allowed.

And that's kind of my point. You've kindly taken the time to re-iterate the viewpoint of the Plugins team around this issue (which really wasn't my intention), and I suspect there are one or two Make posts about it too. Beyond TGMPA, I remember some other plugin authors who weren't happy when this blew up a little while back, and you / the plugins team having to clarify everything multiple times.

I understood this repo to be a rewrite of the rules (though to the casual observer, I can't spot too many differences overall), and therefore an opportunity to add clarifications that would make the rules clearer. The intro page says "renovations in order to clarify intent and meaning".  

I get the benefit of the G18 wording _to the Plugins team_, but trying to nail down some wording that is acceptable for the "it must do something" case would set out the stance (however rare) for this issue, and that _would benefit potential plugin authors_, while still allowing G18 to be invoked if there was still something that didn't fit the explicit wording. 

It's not something I'd push hard on, but when there's an opportunity to reduce ambiguousness for the group of people these rules are generally aimed at, I'd favour clarity over multiple re-explaining :-)

**Comment by Ipstenu** [comment]
> I understood this repo to be a rewrite of the rules (though to the casual observer, I can't spot too many differences overall)

I have to tell you, as someone who has spent much of 2016 working on how to approach this project, this statement is hurtful and somewhat cavalier. If you look https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/ I would hope a 'casual observer' would notice a pretty massive difference in tone, clarity, and intent. If not, then I've absolutely failed at my personal goal, which ... sucks. And I would hope people would pitch verbiage changes to help fix that.

The goal was not to tear down to the ground and rewrite everything. The goal was to come up with a comprehensive set of understandable guidelines for behavior and code that new and old developers would be able to look at and abide by. It was meant to address the _top_ issues we face in the directory. The common problems.

There's absolutely no way to enumerate everything. And in my :mumble: years on the plugin team, 'including other plugins' and libraries/boilerplates/frameworks are actually the edgiest of edge cases. It's only a 'big deal' because every once in a while people will be noisy about it or take it personally when we say "No." to them. People are vocal about a lot of things, like "Your plugin is too dangerous to the average user." We're not going to make a rule about that either. It's just not common enough.

> Yes, this, although I can't remember off the top of my head whether plugins that might otherwise only be sourced from GitHub or other VCS repo, which are bundled (as a zip, which is probably against the rules anyway) as well would be allowed.

This is too broad/obscure for me to think of what you might mean right now.

Can you include (in your own plugin) other plugins that aren't hosted on WordPress.org are a library? Sure. If it's GPL and you remove plugin headers, knock yourself out.

Can you include (in your plugin) a plugin that's hosted on WordPress.org? No. It's hosted on WordPress.org, please make your plugin depend on it.

Will we _ever_ accept libraries? Yes. Technically the JSON API is a library. But it's _also_ a Core Featured Project, and as such an exception. So we look at the whole intent of the plugin beyond just what it does. What it's endgame? Where is it going? With regards to the entire WordPress.org community, is this a benefit _enough_ to outweigh the risks/issues of being a library?

**Comment by GaryJones** [comment]
> I have to tell you, as someone who has spent much of 2016 working on how to approach this project, this statement is hurtful and somewhat cavalier

My sincere apologies for my careless wording. 

Aside: Perhaps when it's all done, a diff between the single-file old rules and single file improved rules would help to showcase the changes to well-meaning idiots like me?

**Comment by Ipstenu** [comment]
It's backwards but - https://github.com/Ipstenu/wporg-plugin-guidelines/compare/OriginalGuidelines?expand=1

**Comment by GaryJones** [comment]
https://github.com/Ipstenu/wporg-plugin-guidelines/compare/6f17338...HEAD#files_bucket looks to be what we're (I'm) after. That shows the "First copylive" commit up until the latest commit on the default branch. As of right now, there's no G15 or G17, as they've not changed.

**Comment by Ipstenu** [comment]
15 barely changed, but 17 totally did so that's wrong somehow. I probably should have checked in the originals and then the updates to make it easier but ... Didn't. Can't go back.
