### ISSUE TITLE
16 - "A complete plugin must be available at the time of submitting the plugin request to the directory."

### ISSUE THREAD

**Issue by dancameron** [Ipstenu/wporg-plugin-guidelines#36]
This second sentence seems to be important enough to gain its own guideline number, or at least have #16 title reference that plugins should be maintained.

i.e. "Directory names for approved plugins that are not used within a reasonable amount of time may be given to other developers."

Maybe a "reasonable amount of time" shouldn't be so subjective, especially since the repo already archives plugins on a schedule. Maybe that archive needs to happen before repo names are given up.

**Comment by Ipstenu** [comment]
You're thinking of how, after 2 years, a plugin drops from the lists?

That's not this. If you submit a plugin, we review it, and 2 years later you've never uploaded it, we MAY give the name away to someone else who asks why they can't use boaty-mcboatface as a plugin slug. There's no archiving or scheduling of this. No one but the admins can even see the unused plugin. And the 'reasonable amount of time' is vague because we've had cases where companies like Facebook submit a plugin, want it reviewed and approved, but don't want to submit the code because that makes it go live right away. Which is fair :) So it's reasonable per the unique situation.

**Comment by dancameron** [comment]
No, I'm mentioning that "reasonable amount of time" is too vague and you might want to use the rules already set in place (which sounds like 2 years). 

I guess I misinterpreted what you're saying though, since "not used" doesn't mean the same thing as not maintained.

**Comment by Ipstenu** [comment]
Yeah, not used literally means you never used it :) And the 2 years thing has nothing to do with it. Totally separate code system. Unmaintained is permitted (if annoying).
