### ISSUE TITLE
Executable code via third-party systems / CNDs not clear

### ISSUE THREAD

**Issue by stuporglue** [Ipstenu/wporg-plugin-guidelines#43]
It might just be late, but I'm having a hard time fully understanding this rule. 

> Externally loading code from documented services is permitted, however all communication must be made as securely as possible. Executing outside code within a plugin when not acting as a service is not allowed, for example:
> ...
> - Calling third party CDNs for reasons other than font inclusions; all non-service related JavaScript and CSS must be included locally

"outside code" -- this means code hosted on a CDN, or provided by a 3rd party API, right? Such as the Google Maps API javascript file? 

"when not acting as a service" -- I'm not sure what this means. When the 3rd party code is not acting as a service? Ie. If the files are just static files hosted on a CDN? Or if a plugin is not acting as a service? 

Sticking with a mapping theme then, does this mean that: 

-  Using the 3rd-party hosted Google Maps API JavaScript (https://maps.googleapis.com/maps/api/js) in your plugin is OK because it's part of a service
- Using the 3rd-party hosted Leaflet.js library (https://npmcdn.com/leaflet@1.0.0-rc.3/dist/leaflet.js) in your plugin is not OK because that's not part of a service? 

Loading Leaflet from the CND is usually desirable since many users will already have it cached. I can't tell if this rule prohibits this sort of thing, especially since the first line says _Externally loading code from documented services is permitted_.

**Comment by Ipstenu** [comment]
No, you understood it perfectly right. It's totally a library vs service thing. If the code being _called_ (not the plugin itself) is a service, then it's permitted.

> Externally loading code from documented services is permitted

* Google Maps is a service - That's fine.

> Executing outside code within a plugin when not acting as a service is not allowed

* leaflet.js is a _library_ - that's not fine

> Loading Leaflet from the CND is usually desirable since many users will already have it cached.

CDN and desirable to _you_ but not necessarily to everyone. What if the CDN is down or blocked for the user? As many things in a plugin that _can_ be local _should_ be local.

Fonts are services, technically, and are a bit of an exception due to size and the fact that .org was doing it too (Google fonts).
