### ISSUE TITLE
Plugin removal

### ISSUE THREAD

**Issue by webzunft** [Ipstenu/wporg-plugin-guidelines#46]
I think it would be good to have a section about plugin removal. When will a plugin be removed? E.g., an unintentional security breach let to this in the past, if I remember correctly, and how the plugin can "recover" from this.

Also a section about the author requesting that his plugin is being removed.

None of this ever happened to me, but I was always asking myself this so maybe the new guidelines could provide the answer.

**Comment by Ipstenu** [comment]
Have a look at https://github.com/Ipstenu/wporg-plugin-guidelines/blob/master/introduction.md#developer-expectations

Second sentence is this:

> Violations may result in plugins or plugin data (for previously approved plugins) being removed from the directory until the issues are resolved.

It's not a guideline, since it's not ... well ... a guideline 😄 A guideline is 'This is what we require you to do...' so we put that in the introduction to explain the more general things about the directory.

**Comment by webzunft** [comment]
Thanks for explaining.
