### ISSUE TITLE
Don't use WP admin email to send spam

### ISSUE THREAD

**Issue by michaeltorbert** [Ipstenu/wporg-plugin-guidelines#52]
Plugins have the privilege of access to quite a bit of data, and there's a lot of responsibility that goes along with that.
Some plugins have automatically sent spam emails to the website owner. At least one well-known plugin currently does it that I know of, other well-known plugins have done it in the past.

**Comment by Ipstenu** [comment]
That would fall under two current guidelines:

1. no unauthorized collection of data (G7)
2. Unethical/immoral (G9) which also mentions not using the server as a botnet

I hesitate at adding that explicitly, but if we did, I think it would fall under G9 perhaps? I'm trying to think of how to word it a little more generically.

* Using the plugin to perform actions not described in the readme.

I may need a more concrete example to be sure of what you mean here. If there IS a plugin hosted on wporg that is collecting your emails and spamming them, or using the plugin itself to email, please contact us with a link to it and if possible how you know it's them (where it is in the code, how you got tricked into signing up etc) - plugins@wordpress.org

**Comment by michaeltorbert** [comment]
@Ipstenu I understand your hesitation at making this explicit in the guidelines, and perhaps it isn't really necessary if it's otherwise covered. My argument for making it explicit would be that part of the problem with the old guidelines (from a plugin developer's perspective) was the perception of over-reliance on general catch-all rules/guidelines that weren't uniformly enforced. This leads to developers not knowing what's acceptable and what isn't acceptable based on different mindsets as a plugin developer, and potentially even cultural differences. Ultimately, this (along with various other reasons) has led to many developers not wanting to host at .org at all in favor of Github or elsewhere.
I'd say that as a general rule, if an expectation from the plugins team isn't reasonably obvious to everyone, it should probably be explicit. Even something like email spam in this case probably isn't being done with bad intentions, and they may just not realize it isn't allowed.

I've sent the email to plugins@.

**Comment by Ipstenu** [comment]
Thanks for the email.

There is a practical reason for not enforcing guidelines uniformly. That is this: There will _always_ be a legit exception to any guideline. That's why they're guidelines, not 'rules', you see.

Is there a reason for a plugin to auto-email you on activation? Yes, I can think of a few. Like think of a security plugin that on activation does a preliminary scan. It _can_ be abused, of course, but we have to weigh the entire situation as a whole. What is the plugin doing, why is it emailing, does it continue to email, is this actually useful or just annoying, etc etc.

> I'd say that as a general rule, if an expectation from the plugins team isn't reasonably obvious to everyone, it should probably be explicit. 

Yeeaaaaaah I don't think that'll ever happen because what's obvious to me may not be to you without an hour of discussion. I spend a lot of time sitting to explain "Well actually, having gone over all of XYZ and talked to the developers and users, we determined this case did make sense and here's why." But if we have to do that for _every_ exception, y'all will never get new approvals!
