### ISSUE TITLE
Add new guideline about menu icons

### ISSUE THREAD

**Issue by Zodiac1978** [Ipstenu/wporg-plugin-guidelines#71]
The Theme Review Team has added a new admin menu requirement for themes in August:
https://make.wordpress.org/themes/2020/08/02/new-admin-menu-page-requirement/

I would like to propose one rule which is mentioned in this blog post to be adapted to plugins as well:
> Use only monochromatic icons. It must account for the admin color scheme.

If images are used this is always breaking the WordPress design, often those images are not retina ready and there not tested with different color schemes. 

The dashicons are already providing a big amount of icons and with tools like https://icomoon.io/app/ you can easily generate an icon font from a SVG to use custom icons. No need to allow design breaking images.

**Comment by Ipstenu** [comment]
That sort of enforcement doesn't scale well with Plugins, due to the difference in how we manage updates. That is. updates to themes are checked. We do not do so for plugins. While we can check on submission, we cannot manage that on subsequent updates, which would lead to people abusing this and no real effective way to manage it :/

I'm incredibly reluctant to add more things to check when there isn't a large benefit, and there's no way to manage it. This is not to say that I don't hate non-monocrome icons as much as the next person, but that at scale, it's not something we could enforce, making it just another guideline people ignore :( 

Unless someone has an idea on how to prevent abuse, I don't think this would be effective.

**Comment by Zodiac1978** [comment]
> Unless someone has an idea on how to prevent abuse

The following ideas come to my mind: 
- We could check on submission to at least prevent new plugins using images.
- We could deprecate the usage of images and recommend using icon fonts.
- We could find those plugins using images with a regex on https://wpdirectory.net/ to inform them.
(For example: https://wpdirectory.net/search/01EMFGG25KSD2C99HQHWJGRQXW)
- Maybe [register_post_type](https://developer.wordpress.org/reference/functions/register_post_type/) is needed to reflect the change (deprecation log/message if a URL to an image is used)
- We could mention the deprecation in blog posts on the make blogs.
- We could try to hide images at this position via CSS in one of the next releases after enough time to get the info around and instead show a generic dashicon.

I tried to tackle this for some time with a userstyle, but if you try to find a good dashicon this is a big task:
https://userstyles.org/styles/159570/de-annoyer

**Comment by Otto42** [comment]
No, we will not be doing that, and I will be asking the themes team why they thought that was okay to do in the first place. Such a rule makes no sense to me, and I'm not okay with it being in place for either themes or plugins.

**Comment by tomjn** [comment]
imo the best solution for the problem of plugins adding noisy and distracting colourful icons would be to add CSS rules to core that make images monochrome and force their hue to match the admin colour scheme.

Otherwise without an automated solution, checking this isn't feasible for the reasons @Ipstenu outlined

**Comment by SergeyBiryukov** [comment]
> imo the best solution for the problem of plugins adding noisy and distracting colourful icons would be to add CSS rules to core that make images monochrome and force their hue to match the admin colour scheme.

That was my thinking here as well, something like:
```
.wp-menu-image img {
	filter: grayscale(100%);
}
```

This would need a core ticket and a dev note once implemented. I haven't found an existing ticket for this, feel free to create one.

**Comment by Otto42** [comment]
That is a topic worthy of core discussion, certainly, however the counter-argument to that is that some plugin or theme would just add CSS to remove said filter for their icon. Which I would say would be a fair thing for them to do.

I'm generally not okay with forcing behaviors for design. It's anti-innovation. While it is reasonable to want a unified design, the core functions allow for putting icons there without forcing them to use dashicons only. If we didn't want it to be open, then it should have been originally written to not be so open and to not have those options. 

I personally don't care whether the icons are colored or not, but I'm not about to enforce my personal preferences on look-and-feel when other opinions are equally valid. If colored icons were a real problem, then okay, have that discussion. But I haven't seen any real world cases of them being a problem, or anybody having any complaints about it. Authors want their menus and things to be attractive and good looking, so having them be ugly or overly garish isn't something they naturally trend towards.

**Comment by Zodiac1978** [comment]
An official recommendation, like mentioned in the comments of the TRT seems to be possible. So this could be a start here.

We do not allow the color schemes in the toolbar on the frontend because this could clash with the design of the page, but we do allow custom colored icons in the dashboard. This confuses me.

Although some people say there are no problems with those images, I have mentioned two reasons why this *could* be something we should fix.

- Images do not scale well and often are not retina ready. This breaks the WordPress backend design and often people do not distinguish between plugins/themes and WordPress core. For them it is *WordPress* itself looking ugly. Do we want that?

- Changing the color schemes does not change the image in 99,9%. Therefore color contrast is missing which is a accessibility problem (although I think myself that this is nit mission critical here) - but it is in every case breaking the design again. Why is this problem? See point 1.

I have written a blog post about this. If someone wants to have some visual examples of the problem:
https://torstenlandsiedel.de/2016/08/02/choose-your-plugin-icons-carefully/

After some WordCamp talks about this (starting at WordCamp Europe in 2014 and not from me) I have recognized that plugins are shifting back from images and are more using dashicons or custom SVGs/Iconfonts/Data-URI. 

I think we should at least document this best practice and mention the color scheme/retina problem somewhere. For example in the plugin handbook.

One last thing: I am not okay with the behavior of closing an issue without discussion and without stating any reasons for it. So I will stop here. I have left all my explanations and ideas. I will not fight any position against people who are in charge and have the power to overrule other teams with just one sentence.

**Comment by SergeyBiryukov** [comment]
> If colored icons were a real problem, then okay, have that discussion. But I haven't seen any real world cases of them being a problem, or anybody having any complaints about it.

... 

> I have written a blog post about this. If someone wants to have some visual examples of the problem:
> https://torstenlandsiedel.de/2016/08/02/choose-your-plugin-icons-carefully/

Just to add some more real world cases of non-monochrome icons being a problem, I have also found a similar post while looking for some examples to test the CSS snippet above: https://ahmadawais.com/bad-icon-wp-admin/

**Comment by Ipstenu** [comment]
> We do not allow the color schemes in the toolbar on the frontend because this could clash with the design of the page, but we do allow custom colored icons in the dashboard. This confuses me.

"We" meaning Theme team. And I honestly don't know why you would do this. The toolbar is for logged in users only, and it does not impact the functionality of the site in any way. It doesn't have aught to do with the design of the site.

> One last thing: I am not okay with the behavior of closing an issue without discussion and without stating any reasons for it. 

As you've noticed, the discussion remains open. :) It's okay to keep discussing. 

There's a fundamental difference between the plugin guidelines and the theme ones. The plugin guidelines are _primarily_ related to spammy/dangerous behavior. Don't do bad things, don't track users, don't trick users. But we have historically shied away from "Don't make your plugin look crappy." mostly because those things out themselves over time on their own.

It is not the auspice of the plugin team to make your plugin look GOOD, it's our responsibility to ensure the plugin works, that it's safe, and that it doesn't encourage bad behavior. And that's really it. If you want to make a super ugly gaudy, admin page, we allow it. And if you want to make colored icons, we may (personally) find it silly, but we'll let you.

**Comment by carolinan** [comment]
The themes team does not allow _any_ changes to the WordPress admin bar.
It doesn't have anything to do with the design of the site, so themes should not touch that.

**Comment by pattonwebz** [comment]
If the discussions are ongoing could the issue be reopened?

Keeping the issue closed indicates that the statement that closed it is the final decision and it is unchangeable regardless of continued discussions.

Additionally a closed issue makes this thread essentially undiscoverable to the majority of people.

**Comment by Otto42** [comment]
I closed the issue because it is essentially a final decision. As ipstenu pointed out, the plugin guidelines do not have anything to say about design or looks or any other elements of the plugins outside of their existing purview. The plugins team does not monitor those elements at all, and really has no desire or intent to monitor them.

The guidelines are about preventing bad behavior and keeping plugins working and functional for users. Enforcing some kind of design pattern doesn't fall into that category.

If you want to talk about colored icons and such, then that would be more in the scope of core, or apparently in the theme review channel, however this simply isn't something that the plugin team wishes to add to the guidelines. It's out-of-scope.

**Comment by pattonwebz** [comment]
> If you want to talk about colored icons and such, then that would be more in the scope of core, or apparently in the theme review channel, however this simply isn't something that the plugin team wishes to add to the guidelines. It's out-of-scope.

So it's not really up for discussion? I get you ;)

**Comment by Otto42** [comment]
Not sure I said that. You can discuss the idea all you want, but it doesn't make sense to add it to the plugin guidelines, for the reasons ipstenu pointed out.  We don't have any guidelines on adding admin menus or how many, or even that the settings pages for a plugin use the core functions for doing so. 

We have lots of recommendations for following the look-and-feel of the core code, but there's no hard and fast rules for doing such. Plugins are free to innovate and step outside the box of the WordPress code patterns if that makes sense for them to do so. Users tend to choose based on their own preferences, so that tends to work itself out, by and large, through the power of people's choice.

**Comment by pattonwebz** [comment]
> Not sure I said that. You can discuss the idea all you want, but it doesn't make sense to add it to the plugin guidelines, for the reasons ipstenu pointed out.

Applogies if that's not what you meant - but you did say your decision was final and thus the implications of that is father discussion here is either irrelevant or a waste of people energy. 

It is what it is though and I really have no concern myself with plugin guidelines - I just wanted to try and make sure voices were heard when they wanted to speak.

**Comment by tomjn** [comment]
I think the closure could have been worded better, but that the plugin guidelines aren't really the place to make meaningful progress addressing this. If nobody has created a ticket on Trac we can continue this in then this needs to instead move to somewhere we can discuss the hole in automation for plugins that prevents this from being feasible nevermind desirable.

**Comment by Ipstenu** [comment]
> If the discussions are ongoing could the issue be reopened?

IF the discussion pivoted to something that would be actionable by the plugins team, yes. So far? Not so much. Hence why being closed (but open for comment) is the correct choice. Someone down the line may have an 'Ah hah! Here's how we could automate this!'

**Comment by pattonwebz** [comment]
A closed thread sends the message that final decision is final and was made prior - at the time of the closing comment. There is no other way to see it from my perspective. 

The thread is undiscoverable and appears the idea was already rejected. Why would more actionable comments be left here when it is indicated nothing is open for change?

**Comment by Ipstenu** [comment]
Okay this is WAY off topic, but I must stress: If ANY issue on ANY Github repo remains open for comment, then it's open for comment. 

Also it's totally discoverable -- still shows up as a closed issue if you searched. 

It is neither locked nor deleted, so please feel free to share any practical ideas that you think should be adopted as a guideline change. Right now, as the idea was pitched, it's not going to be included as Otto (and I) feel it's out of scope for what the current guidelines are. I have no plans to delete or lock this, since someone could come up with something else.

Until then, I _recommend_ if you wanted to pitch this as a core idea (to force monochrome) then that would be a great path forward.

**Comment by pattonwebz** [comment]
Someone should open that core ticket if the change is important for them. What is important for me is that users feel it is ok to make suggestions like this and for them to be discussed - in the open - with others that are willing to hear them out and not simplly close the issue out without allowing the discussion to happen. If it feels unwelcoming to me, and to the OP here, then is it unwelcoming for others too?
