### ISSUE TITLE
Clarifying acceptability of reviews for pro/paid extensions for a free plugin on .org in the handbook

### ISSUE THREAD

**Issue by jackmcconnell** [Ipstenu/wporg-plugin-guidelines#75]
Whilst it's clear (to me at least) that plugin authors with a free plugin available on .org cannot provide support for pro/paid extensions/SaaS components through the support forums, it isn't clear (to me at least) how and if reviews of those paid products are allowed on .org, particularly if they're an upsold product within the plugins readme.
Whilst [this post](https://make.wordpress.org/plugins/2016/05/03/handling-bad-reviews/), written 5-years ago at time of writing, does clarify this to some extent, it doesn't go into much detail and isn't particularly professional in it's approach to helping explain this scenario, nor does it seem to constitute part of the official plugin handbook. 

To quote: 
> If you upsell your plugin’s pro version in the free one, and someone leaves a bad review because the pro version they bought, on the basis of your free one, is bad, congratulations. The review stays. You opened the door with your upsell, encouraging them to do this, and that experience reflects on your plugin as a whole.

I feel one thing that could be clarified in the guidelines is where the line is drawn between support and reviews from a .org standpoint. Issues around reviews for paid products can arise where free plugins have one author but paid plugins are by multiple authors that share a common author, or are authored by the same company. Additionally a Pro version of a plugin may offer substantially different functionality that has no relation on the free plugin, but seems to be governed by the same rules as the free plugin, from a .org standpoint.

I guess what i'm trying to say is that: 
If .org provides support and reviews systems for a free plugin, and an author upsells a product through the readme and also provides support and review systems for those upsells separately and advertises this in the same way, why is support for paid products not permitted on .org but reviews for paid products are? 

For transparency, I've been a plugin author for 8-years and the above hasn't really affected me, but I would like to see it clarified for the benefit of others, particularly new plugin authors that may only use the plugin handbook as their go to source for guidance should this issue arise for them.

**Comment by Ipstenu** [comment]
I'm closing this ONLY because it's not a plugin guideline, it's a forum one. So you should take that up with them for clarity.

> I feel one thing that could be clarified in the guidelines is where the line is drawn between support and reviews from a .org standpoint. 

Honestly? It's a case by case basis, since people are pretty inconsistent in how they ask for help. The forum moderators handle this, though, which is why I said you have to ask them. It's not OUR guideline, it's theirs.

**Comment by jackmcconnell** [comment]
@Ipstenu Can you please direct me as to where I can reach the appropriate people? I have to say, I'm a bit confused. Perhaps you can clarify, once i've confirmed a response from the appropriate people, can this be incorporated into the plugin guidelines?

**Comment by Ipstenu** [comment]
You can ask them in Slack in the #forums channel. 

It's unlikely this would be pulled into the developer guidelines, since if it's clarified in the forum guidelines, and we require compliance with that, then I believe we're covered.

> I feel one thing that could be clarified in the guidelines is where the line is drawn between support and reviews from a .org standpoint.

That would be a job for the FORUM guidelines, as it would need to cover themes as well, and doing it three times seems a little redundant :)

**Comment by jackmcconnell** [comment]
@Ipstenu Thanks for bearing with me whilst I ask some questions. It's probably because i'm not aware of the inner workings of .org's structure that I find this so confusing. 

So the forum (support) guidelines govern plugin reviews as well - is that right? 
If this is already covered in the theme guidelines, how is a plugin developer able to be better signposted to that information?

**Comment by fierevere** [comment]
related Slack conversation follow-up: https://wordpress.slack.com/archives/C02RQC6RW/p1621582770245500

**Comment by Ipstenu** [comment]
Reviews happen in the forums.

The forums team monitors and manages the forums. If they need the plugin team, or the theme team, for backup, they ask :) But that's why the PLUGIN guidelines say "If you use the forums, you have to follow the forum guidelines."

The fundamental reason I'm being 'short' here is that I don't want to step on their toes or get you more confused :) 

> If this is already covered in the theme guidelines, how is a plugin developer able to be better signposted to that information?

To be honest, I've not actually looked in detail at the THEME guidelines recently. Their guidelines have always been different than plugin guidelines. The **plugin guidelines** link you to the forum guidelines, though, which is sufficiently "signposted"

**Comment by jackmcconnell** [comment]
Ok @Ipstenu thanks. I understand the difference between the forums, plugin, and theme teams now. Thanks for explaining :)
