### ISSUE TITLE
Are unreasonable technical code reviews expected?

### ISSUE THREAD

**Issue by clivezhg** [Ipstenu/wporg-plugin-guidelines#79]
Once I submitted a plugin and it was accepted (https://wordpress.org/plugins/more-lang/), it got very high user score.
However, the plugin was closed without any real code issue, the reviewer pushed a few unreasonable code change requirements (and those review points are not documented in this project) .
Some review details are here: https://github.com/clivezhg/Unreasonable-Code-Reviews/. I would like to know whether what the reviewer did is expected.

**Comment by jrfnl** [comment]
Just read the report. None of the requested changes sound unreasonable to me and all are in the guidelines: secure your code.

**Comment by Ipstenu** [comment]
Your email bounced, Clive, and the guidelines also say (in developer expectations) that we need it to work.

You’ve got some basic sanitization issues and as the email explained, we do require any closed plugin to correct them so that less ethical security companies won’t attack you and smear your reputation as well as attack the directory and discredit everyone else.

That was 18 months ago, man. Ball is in your court. The review is valid and stands.

**Comment by clivezhg** [comment]
> Just read the report. None of the requested changes sound unreasonable to me and all are in the guidelines: secure your code.

I douted whether you read the report carefully. More-Lang is a multilingual plugin, its saved content should be the mulgilingual equivalents of the Wordpress Core data. Your guildelines add some restrictions to the plugins, but the Wordpress Core doesn't follow these guidelines. So, how can More-Lang keep the same data formats with Wordpress Core, if More-Lang santinize some data but Wordpress Core doesn't?

**Comment by clivezhg** [comment]
> Your email bounced, Clive, and the guidelines also say (in developer expectations) that we need it to work.
> 
> You’ve got some basic sanitization issues and as the email explained, we do require any closed plugin to correct them so that less ethical security companies won’t attack you and smear your reputation as well as attack the directory and discredit everyone else.
> 
> That was 18 months ago, man. Ball is in your court. The review is valid and stands.

Hi Ipstenu, there's no any sanitization issue in  Moe-Lang, see the above explanation.
And you were the initial reviewer of More-Lang, all the so-called issues alread existed in the first version, so do you admit it's your mistake to let it pass?
Because I'm busy on other stuff, and I found this place lately, I don't  appeal to re-open it anymore. I just want to hear more ideas about it, because the last reviewer was unable to convince me in technical part (at last, he/she closed it for something like "we can do anything in our space").

**Comment by Ipstenu** [comment]
I’m no more perfect than you are, Clive. And since you’ve said you’re busy and have no plan to reopen, I’m locking this as it’s a non productive complaint and not about the guidelines anyway.

1. the security issues are real
2. no review is 100% perfect and everyone makes mistakes
3. it’s a reasonable re-review.

**Comment by Ipstenu** [comment]
Updating to point this out. This complaint, valid or not, is _NOT_ about the Plugin Developer Guidelines or expectations.

This is a complaint about the code review of a plugin that was closed.

As such its **OFF TOPIC** for this GitHub repository
