### ISSUE TITLE
Don't allow repurposing a plugin

### ISSUE THREAD

**Issue by Zodiac1978** [Ipstenu/wporg-plugin-guidelines#82]
_Looking at the existing discussions about explicit rules, I think this will be closed as not enforceable, but I still wanted to add this idea. At least to document it for people looking for such a rule._

Sometimes a plugin gets popular and has a decent amount of active installation, and then it gets acquired by a new company and this new owner re-purposes the plugin using the user base for advertising a pro version.

Examples can be found here:
https://wptavern.com/profilepress-rebrands-and-repurposes-wp-user-avatar-now-a-membership-plugin-users-revolt-via-the-wordpress-review-system

I don't think there is a rule at the moment to prevent this. Looking at the comments and reviews, this is something people do not like, but as you can delete the plugin maybe there is no real damage, and you decide we cannot enforce such a rule in the first place.

**Comment by Ipstenu** [comment]
I preface this with the reminder that this situation is _NOT_ unique to WP.org or opensource. Many a commercial tool has totally redone everything and become something entirely different.

the tl;dr is "If you want to change everything and upset your users, on your head be it"

The first step in potential enforcement would be ... You'd have to very clearly define what is a 'repurpose.' 

A rebranding (Twitter -> X) is often seen as "Silly but fine" -- IMO rebranding is a massive thing to consider as it can cause the loss of standing. IIRC there was an email/newsletter plugin that had the slug wysiwyg-email (or something to that effect) and they totally rebranded but were 'stuck' with the old permalink. Yoast SEO is stuck with 'wordpress-seo' forever, and they very much would be fools to close it and start over, because you can't migrate users (technical limitations). Cleverly, the Yoast folks went with a new display name that was distinctive. So there, you see, rebranding is totally fine.

But _repurposing_ is messier. What is an acceptable 'repurpose'? Is adding features a repurpose if you're not removing the original core functionality? For example you mention this:

>  this new owner re-purposes the plugin using the user base for advertising a pro version.

That has a lot more nuance than just the wp-user-avatar plugin. That was converted into a totally different plugin, which is annoying as anything. And flat out moving _everything_ to a pro-plugin and leaving just a placeholder with no-code is already a guideline violation (see Guideline 16 - you have to submit a functional plugin, which logically extends to "your plugin has to actually DO something!").

But the way you phrased it, let's say this...

I have a plugin that makes local avatars. I decide I want to make money, so _remove_ all the cool features, change the hooks, and make the wp.org plugin do nothing except upload and assign one avatar to people. Now all the cool stuff is on a pro-add-on.

Would that be considered a repurpose? It's actually what we tell people to do if they want _part_ of a plugin to be premium! "Remove the features you want people to pay for." It didn't really repurpose the plugin, the end goal is still the same, it's just strongly limited. That should be allowed!

What wp-user-avatar did was take a simple plugin and add a whole mess of features no one really cared about (the membership stuff). Arguably they did it to leverage the existing user base (that's my interpretation, it may be incorrect!) and hook the users into buying the add-ons. If they add on features no one wants, but keep the old one, it's squiffy, but technically allowed. 

There are just so many possible permutations, it would be very difficult to craft a guideline that covered enough of them to make a significant dent. Not to say it's impossible! I would love to see people manage to come up with one that's fair to all.

**Comment by Zodiac1978** [comment]
I'm not a native speaker, and therefore misunderstandings seem to be inevitable.

> And flat out moving everything to a pro-plugin and leaving just a placeholder with no-code is already a guideline violation

This was not meant by me, I was just trying to summarize what I _think_ is the idea behind those re-purposing in the WP Tavern article.

Or, as you are phrasing it: 
> Arguably they did it to leverage the existing user base 

But you wrote two things:
> the tl;dr is "If you want to change everything and upset your users, on your head be it"
and
> If they add on features no one wants, but keep the old one, it's squiffy, but technically allowed.

So I assume you are trying to tell me that this allowed, and we can't change it. Two times.

But then you write this last paragraph:
> There are just so many possible permutations, it would be very difficult to craft a guideline that covered enough of them to make a significant dent. Not to say it's impossible! I would love to see people manage to come up with one that's fair to all.

And maybe this is a cultural difference, but for me, it is confusing, if you end up with a paragraph that is telling me, it _could_ be working, if handled _very_ well, although you told me the opposite twice. I do not know if this is what you really want to say, or if this is a kind way to end, although this would never be considered by you or anyone else.

As I already stated, I'm not a native speaker and therefore will not be able to formulate a guideline so well it will handle all those possible permutations.

Therefore, I'm closing this now. If someone finds this issue and thinks he/she can phrase something which could be working, feel free to re-open this issue or open up a new one.

**Comment by Ipstenu** [comment]
@Zodiac1978 I was discussing two aspects:

**Today**

Right now, using the example you provided, what they did is 100% permissible and they can suffer the fallout.

**The future**

While I think it would be very very very x100 hard to come up with a way to craft a guideline that covers all the possible permutations of what is and isn't allowed. But it would be very cool if someone did.

That's why I said this:

> The first step in potential enforcement would be ... You'd have to very clearly define what is a 'repurpose.'

If someone (anyone) can do that, then you have a starting point. Until then, this is a nice idea but impossible to make an enforceable guideline.

Also? No matter what _every single guideline can be changed_. We just have to be smart about it :)
