### ISSUE TITLE
Third-party ads vs upselling/add-ons

### ISSUE THREAD

**Issue by JDGrimes** [Ipstenu/wporg-plugin-guidelines#9]
I think that part of [section 11](https://github.com/Ipstenu/wporg-plugin-guidelines/blob/master/guideline-11.md) isn't completely clear in regard to the difference between third-party advertising vs links to the plugin/author site vs advertising relating directly to the plugin itself (upselling, advertising add-ons, etc.).

Specifically these two paragraphs:

>Banner or text link advertising should be excluded from a plugin, including on its settings screen. Advertising on the WordPress Dashboard is historically ineffective, as ideally users rarely visit these screens. Similarly, third party ad systems rarely permit their usage on admin-only screens (notably, Google Ads does not permit its usage there); if they do permit back-end ads, the quality will be low as those systems cannot see the page content to determine good ads. Abusing the guidelines of an advertising system will result in such actions reported to the advertising system.

>Developers are welcome and encouraged to include links to their own sites or social networks, as well as locally (within the plugin) including images to enhance that experience.

The first paragraph starts off sounding like it might be discouraging all advertising, even in the context of upselling. Then when it starts talking about third-party ad services, it sounds like it might not be talking about advertising related to the plugin at all, and that feeling is then enforced somewhat by the second paragraph.

**Comment by Ipstenu** [comment]
It's both.

Advertising within your plugin admin, including upselling, is discouraged. Users don't like it (go read all the 1-star reviews, and you'll see a LOT of people complaining about how annoying it is). 

On top of general advertising, 3rd party ads are not okay because they're tracking users (and some like Google) don't allow it at all on WP Admin.

So we're trying to cover two things.

**Comment by dancameron** [comment]
I agree this needs to be clarified though; covering two distinct methods of advertising with one guideline while one to be simply "discouraging" is misleading and open for abuse.

**Comment by Ipstenu** [comment]
I'm going to try and break down the intent and then if you can come up with suggestions for better wording, I appreciate it. This is clear to me, but it's already abused :/

Guideline 11 is "Don't spam the wp-admin dashboard" one.

1. Making the dashboard a billboard is annoying and people hate you.
2. Putting your ads (be they your own or 3rd party) on your plugin settings pages is discouraged.
3. Any ads on your plugin settings page is going to suck anyway, so really why are you doing this?
4. Reminder: some ads like Google don't even allow you to put their ads on wp-admin so don't do it

Since we already _have_ a guideline about not tracking users [see 07](https://github.com/Ipstenu/wporg-plugin-guidelines/blob/master/guideline-07.md) it's not necessary to reiterate that we don't let you use tools that may track users without consent.

**Comment by tnorthcutt** [comment]
> Advertising within your plugin admin, including upselling, is discouraged.

Including some "do this, don't do that" examples, with screenshots, could go a long way toward clarifying things here. I understand the reluctance to draw a hard line, but without one, it's hard for developers to know how far is "too far".

**Comment by Ipstenu** [comment]
The reluctance of saying "This is too far" is that people will (and have) gotten within an inch of the line but not crossed it.

Here's an example of a notice/alert type ad (but easily extends to banners):

* If it's on your plugin settings page, it's annoying but okay
* If you have it on _every_ page after an install/upgrade, but it's dismissible, it's annoying but okay
* If you have it on every dashboard page and it's _NOT_ dismissible, it's not okay

Is that helpful?

**Comment by tnorthcutt** [comment]
@Ipstenu yep, those are very helpful. Like I said, I understand the reluctance, but ultimately I think clarity is important here. And, if you guys think that wherever that line is is too far, by all means move it back so that within an inch of it is palatable.

**Comment by Ipstenu** [comment]
How does that re-write sound? (see the pull request)
